[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "scoutmaster-api"
version = "0.1.0"
description = "ScoutMaster API client"
requires-python = ">=3.9"

[tool.setuptools]
packages = ["scoutmaster"]
